POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title" : "The second title done with users", 
  "author": "M.Mshr2",
  "url" : "Second-try.com",
  "likes": 23,
  "userId":"5f7d660ba90bea009c3f71b8"
}